# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.5.3.dev66+ga31b4826.d20230714'
__version_tuple__ = version_tuple = (1, 5, 3, 'dev66', 'ga31b4826.d20230714')
