# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.0.0a1.dev13+g6778de24.d20230714'
__version_tuple__ = version_tuple = (2, 0, 0, 'dev13', 'g6778de24.d20230714')
